-- A document waiting on a human to say who a vendor is.
--
-- AD-8: an extracted vendor name that resolves to no known vendor never
-- auto-creates one. It stops here instead, and a treasurer decides. This table
-- is what "stops here" means.
--
-- It is deliberately NOT a fifth extraction state. Extraction succeeded: the
-- provider answered, the records validated, they are stored, and
-- document.extraction_state is `read`. What is pending is vendor resolution,
-- which is a different question about the same document. Story 1.5d fixed the
-- extraction vocabulary at four states and made `extracting` a rendered state
-- rather than a stored one; UX-DR12's "quarantine-waiting" is derived the same
-- way, from `read` plus a row in here.

create table quarantine_item (
  id              uuid        primary key default uuidv7(),

  -- Cascade, because an item without its document is not a question anybody can
  -- answer -- it is debris that still satisfies a foreign key. Migration 006
  -- makes the same argument for extraction rows.
  document_id     uuid        not null references document (id) on delete cascade,

  -- The name as the document said it, not folded. A treasurer is being asked
  -- "who is this?", and the answer depends on seeing what was actually read.
  -- The normalised form below is a comparison key and is no use to a human.
  extracted_name  text        not null,

  -- Generated from migration 009's function, not a second rule of its own.
  --
  -- This is what makes "the same name" mean the same thing to quarantine as it
  -- does to the vendor table. With two definitions, one document could be held
  -- twice for one vendor under two spellings -- which is the defect the whole
  -- of epic story 1.6 exists to prevent, wearing a different hat.
  normalised_name text        generated always as (vendor_normalised_name(extracted_name)) stored,

  created_at      timestamptz not null default now(),

  -- Two measurements answering two questions, as migration 009 arrived at after
  -- getting it wrong twice. `char_length(btrim(...)) between 1 and 200` is the
  -- shape that failed: it lets 'x' plus three hundred trailing spaces through,
  -- because btrim removes the ends before counting.
  --
  --   char_length(extracted_name) <= 200  -- how much is actually stored
  --   char_length(btrim(...))     >= 1    -- whether anything is actually there
  constraint quarantine_item_name_length check (
    char_length(extracted_name) <= 200
    and char_length(
      btrim(extracted_name, ' ' || chr(9) || chr(10) || chr(13) || chr(11) || chr(12) || chr(160) || chr(8239))
    ) >= 1
  )
);

-- Composite, and both halves earn their place.
--
-- Per document, because re-extracting one document must not stack a second copy
-- of the same question (AD-13 makes re-ingest ordinary, and a retry is ordinary
-- too). Per name, because one document can yield several records and two
-- unknown vendors on it are two decisions.
--
-- Keyed on the *normalised* name so a second spelling collides rather than
-- inserting. And NOT keyed on the name alone: two invoices from one unfamiliar
-- vendor are two documents waiting, and a global unique index would silently
-- hold only the first.
create unique index quarantine_item_document_name_key
  on quarantine_item (document_id, normalised_name);

-- Migration 003 revoked default SELECT for watchdog_reader, so read access is an
-- explicit decision per table.
--
-- Granted: story 1.6c renders this queue, and the read path is how it gets there.
--
-- SELECT only, and the DELETE half matters most. Clearing a hold is exactly how
-- a human's decision would get skipped, and AD-8 exists to keep that human in
-- the loop -- so the LLM-driven query path must not be able to do it.
grant select on quarantine_item to watchdog_reader;

comment on table quarantine_item is
  'A document held because an extracted vendor name resolved to no known vendor (AD-8). Not an extraction state: extraction succeeded and document.extraction_state is ''read'' -- this is vendor resolution pending. Readable by watchdog_reader so the queue can be rendered; never writable by it, because clearing a hold would skip the human.';
comment on column quarantine_item.extracted_name is
  'As the document said it. Shown to a treasurer, who is being asked to recognise it.';
comment on column quarantine_item.normalised_name is
  'Generated by vendor_normalised_name(), the same rule the vendor table uses for identity. One definition, so quarantine and vendor cannot disagree about whether two spellings are one name.';
